django_black_belt/black_belt_test/apps/black_belt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'my_index'),
    url(r'^add$', views.add, name = 'my_add'),
    url(r'^new$', views.new_info, name = 'my_new_info'),
    url(r'^destination/(?P<id>\d+)$', views.destination, name = 'my_destination'),
    url(r'^join/(?P<id>\d+)$', views.join, name ="my_join")


]

django_black_belt/black_belt_test/apps/login_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name ="my_index"),
    url(r'^validate_register$', views.register, name ="my_register"),
    url(r'^validate_login$', views.login, name ="my_login"),
    url(r'^success$', views.success, name = "my_success"),
    url(r'^logout$', views.logout, name = 'logout')
]

django_black_belt/black_belt_test/black_belt_test/urls.py
from django.conf.urls import url, include

urlpatterns = [
	url(r'^', include('apps.login_registration.urls', namespace = "logreg")),
    url(r'^test/', include('apps.black_belt.urls', namespace = 'black_belt')),

]

django_black_belt/black_belt_test/apps/black_belt/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_registration.models import User
from datetime import datetime
import re
class TravelManager(models.Manager):
	def date_valid(self, start, end):
		now = datetime.now()
		start = datetime.strptime(start, "%Y-%m-%d") 
		end = datetime.strptime(end, "%Y-%m-%d")
		if start < now:
			return False
		if end < now or end < start:
			return False
		return True
	def trip_name(self, plan, destination):
		NAME_REGEX = re.compile(r'^[a-zA-Z-]{2,}$')
		if not NAME_REGEX.match(destination):
			return False
		elif not NAME_REGEX.match(plan):
			return False
		return True
class Travel(models.Model):
	user = models.ForeignKey(User)
	destination = models.CharField(max_length = 255)
	start = models.DateField()
	end = models.DateField()
	plan = models.CharField(max_length = 255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = TravelManager()

class Guest(models.Model):
	travel = models.ForeignKey(Travel)
	user = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

django_black_belt/black_belt_test/apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt

class UserManager(models.Manager):	
	def login_valid(self, username, password):
			user = User.objects.get(username = username)
			if user:
				password = password.encode()
				if bcrypt.hashpw(password, user.password.encode()) ==  user.password.encode():
					return True
				else:
					return False
			else:
				return False

	def register(self, first_name, username, password, confirm):
		NAME_REGEX = re.compile(r'^[a-zA-Z-]{3,}$')
		PASSWORD_REGEX = re.compile(r'^.{8,}$')
		if not NAME_REGEX.match(first_name):
			return False
		elif not NAME_REGEX.match(username):
			return False
		elif not PASSWORD_REGEX.match(password):
			return False
		elif  not password == confirm:
			return False
		else:		
			return True

class User(models.Model):
	first_name = models.CharField(max_length = 45)
	username = models.CharField(max_length = 45)
	password = models.CharField(max_length = 255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = UserManager()

django_black_belt/black_belt_test/apps/black_belt/views.py
from django.shortcuts import render, redirect
from ..login_registration.models import User
from .models import Travel, Guest
import bcrypt
from django.core.urlresolvers import reverse

def index(request):
	request.session['message'] = " "
	request.session['login_message'] = ""
	request.session['register_message'] = ""
	id = request.session['id']
	user = User.objects.get(id=id)
	context={		
		'user': User.objects.get(id=id),
		'my_travels':Guest.objects.filter(user_id=id),
		'other_travels':Travel.objects.exclude(user__id=id).exclude(guest__user_id=user.id),
	}
	return render(request, 'black_belt/index.html', context)
def add(request):
	id = request.session['id']
	context={
		'user': User.objects.get(id=id),
		'my_travels':Travel.objects.filter(user_id=id),
	}
	return render(request, 'black_belt/add.html', context)
def new_info(request):
	add_valid = Travel.objects.date_valid(request.POST['start'], request.POST['end'])
	add_valid_info = Travel.objects.trip_name(request.POST['destination'], request.POST['plan'])
	if add_valid and add_valid_info:
		request.session['message'] = " "
		user = User.objects.get(id =request.session['id'])
		travel=Travel.objects.create(user = user, destination = request.POST['destination'], plan = request.POST['plan'], start = request.POST['start'], end = request.POST['end'])	
		guest = Guest.objects.create(travel=travel, user = user)
		return redirect(reverse('black_belt:my_index'))
	elif not add_valid_info:
		request.session['message'] = "Need to input destination and plan"
		return redirect(reverse('black_belt:my_add'))

	else:
		request.session['message'] = "Invalid date choice"
		return redirect(reverse('black_belt:my_add'))

def destination(request, id):
	travel= Travel.objects.get(id=id)
	context={
		'travel': Travel.objects.get(id=id),
		'guests': Guest.objects.filter(travel=travel)
	}
	return render(request, 'black_belt/destination.html', context)
def join(request, id):
	user = User.objects.get(id =request.session['id'])
	travel=Travel.objects.get(id=id)
	guest = Guest.objects.create(travel=travel, user=user)
	user.save()
	return redirect(reverse('black_belt:my_destination', kwargs={'id':id}))

django_black_belt/black_belt_test/apps/login_registration/views.py
from django.shortcuts import render, redirect
from ..login_registration.models import User
import bcrypt
from django.core.urlresolvers import reverse

def index(request):
	try:
		request.session['message']
	except:
		request.session['message'] = ''
	return render(request, 'login_registration/index.html')
def register(request):
	info_validate = User.objects.register(request.POST['first_name'],request.POST['username'],request.POST['password'], request.POST['confirm']) 
	password = request.POST['password']
	if info_validate:
		request.session['message'] = " "
		request.session['first_name'] = request.POST['first_name']
		password = password.encode('utf-8')
		hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
		first_name = request.POST['first_name']
		username = request.POST['username']
		User.objects.create(first_name = first_name, username = username, password = hashed)
		request.session['id'] = User.objects.get(username=request.POST['username']).id
		return redirect(reverse('black_belt:my_index'))
	elif not info_validate:
		request.session['message'] = "First Name required and must letters\r\n Username required and must have letters \r\n Password Required with no fewer than 8 characters and must match passwowrd confirmation"
		return redirect(reverse('logreg:my_index'))
def login(request):
	login_validate = User.objects.login_valid(request.POST['username'], request.POST['password'])
	if login_validate:
		request.session['message'] = ''
		request.session['id'] = User.objects.get(username=request.POST['username']).id
		request.session['first_name'] = User.objects.get(username =request.POST['username']).first_name
		return redirect(reverse('black_belt:my_index'))
	elif not login_validate:
		request.session['message']= 'Wrong login credentials'
	return redirect(reverse('logreg:my_index'))
def success(request):
	return render(request, 'black_belt/index.html')
def logout(request):
	request.session.pop('id')
	return redirect(reverse('logreg:my_index'))

django_black_belt/black_belt_test/apps/black_belt/templates/black_belt/add.html
<!DOCTYPE html>
<html>
	<head>
		<title>Add Plan</title>
	</head>
	<body>
		<a href = "{% url 'logreg:logout' %}">Logout</a>
		<a href="{% url 'black_belt:my_index' %}">Home</a>
		{% if not request.session.message is '' %}
			<h3>{{request.session.message}}</h3>
		{% endif %}
		<h1>Add a Trip</h1>
		<form action ="{% url 'black_belt:my_new_info' %}" method ="post">{% csrf_token %}
			<label>Destination:</label><input type ="text" name ="destination"><br>
			<label>Description:</label><textarea name ="plan" rows=20 cols=100></textarea>
			<label>Travel Date From:</label><input type ="date" name ="start"><br>
			<label>Travel Date To:</label><input type ="date" name ="end"><br>
			<input type ="submit" name = "submit" value="Add">
		</form>
	</body>
</html>

django_black_belt/black_belt_test/apps/black_belt/templates/black_belt/destination.html
<!DOCTYPE html>
<html>
	<head>
		<title>Destination</title>
	</head>
	<body>
		<a href = "{% url 'logreg:logout' %}">Logout</a>
		<a href="{% url 'black_belt:my_index' %}">Home</a>
		<h1>{{travel.destination}}</h1>
		<p>Planned by: {{travel.user.first_name}}</p>
		<p>Description: {{travel.plan}}</p>
		<p>Travel Date From: {{travel.start}}</p>
		<p>Travel Date To: {{travel.end}}</p>
		<h1>Other users joining the trip</h1>
			{% for guest in guests %}
				<p>{{guest.user.first_name}}</p>
			{% endfor %}
	</body>
</html>

django_black_belt/black_belt_test/apps/black_belt/templates/black_belt/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Travel Dashboard</title>
	</head>
	<body>
		<a href = "{% url 'logreg:logout' %}">Logout</a>
		<h1>Hello {{user.first_name}}!</h1>
		<div id="travel_table">
			<h3>Your Trip Schedules</h3>
			<table>
				<thead>
					<tr>
						<th>Destination</th>
						<th>Travel Start Date</th>
						<th>Travel End Date</th>
						<th>Plan</th>
					</tr>
				</thead>
				<tbody>
					{% for my_travel in my_travels %}
						<tr>
							<td><a href = "{% url 'black_belt:my_destination' id=my_travel.travel.id %}">{{my_travel.travel.destination}}</a></td>
							<td>{{my_travel.travel.start}}</td>
							<td>{{my_travel.travel.end}}</td>
							<td>{{my_travel.travel.plan}}</td>
						</tr>
					{% endfor %}
					
				</tbody>
			</table>
		</div>
		<div id ="other_travel">
			<h3>Other User's Travel Plans</h3>
			<table>
				<thead>
					<tr>
						<th>Name</th>
						<th>Destination</th>
						<th>Travel Start Date</th>
						<th>Do you Want to Join?</th>
					</tr>
				</thead>
				<tbody>
					{% for other_travel in other_travels %}

							<tr>
								<td>{{other_travel.user.first_name}}</td>
								<td><a href = "{% url 'black_belt:my_destination' id=other_travel.id %}">{{other_travel.destination}}</a></td>
								<td>{{other_travel.start}}</td>
								<td>{{other_travel.end}}</td>
								<td><a href = "{% url 'black_belt:my_join' id=other_travel.id %}">Join</a></td>
							</tr>

					{% endfor %}
				</tbody>
			</table>
		</div>
		<a href ="{% url 'black_belt:my_add' %}"> Add Travel Plan</a>
	</body>
</html>

django_black_belt/black_belt_test/apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login & Reg | Home</title>
	</head>
	<body>
		<h1>Welcome!</h1>
		<h1>Registration</h1>
		{% if not request.session.message is '' %}
			<h3>{{request.session.message}}</h3>
		{% endif %}
		<form action ="{% url 'logreg:my_register' %}" method="post">{% csrf_token %}
			<label>Name:</label><input type = "text" name ="first_name"><br>
			<label>Username:</label><input type = "text" name ="username"><br>
			<label>Password:</label><input type = "text" name = "password"><br>
			<label>Confirm:</label><input type = "text" name = "confirm"><br>
			<input type = "submit" value = "Register">
		</form>
		<h1>Login</h1>
		<form action ="{% url 'logreg:my_login' %}" method="post">{% csrf_token %}
			<label>Username:</label><input type = "text" name="username"><br>
			<label>Password:</label><input type = "text" name = "password"><br>
			<input type = "submit" value = "Login">
		</form>
	</body>
</html>

django_black_belt/black_belt_test/apps/login_registration/templates/login_registration/success.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login & Reg | Success</title>
	</head>
	<body>
		<h1>Success! Welcome, {{request.session.first_name}}!</h1>
		<p>Successfully {{request.session.regorlogin}}</p>
	</body>
</html>