django_black_belt/retake_black_belt_test/apps/black_belt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "my_index"),
    url(r'^poke/(?P<id>\d+)$', views.poke, name ="my_poke")
]

django_black_belt/retake_black_belt_test/apps/login_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name ="my_index"),
    url(r'^validate_register$', views.register),
    url(r'^validate_login$', views.login),
    url(r'^success$', views.success),
    url(r'^logout$', views.logout, name = 'logout')
]

django_black_belt/retake_black_belt_test/retake_black_belt_test/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^home/', include('apps.black_belt.urls', namespace = "black_belt")),
    url(r'^', include('apps.login_registration.urls', namespace = "logreg")),
]

django_black_belt/retake_black_belt_test/apps/black_belt/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_registration.models import User

class Poke(models.Model):
	poker = models.ForeignKey(User, related_name= "poker")
	pokee = models.ForeignKey(User, related_name = "pokee")
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

django_black_belt/retake_black_belt_test/apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from datetime import datetime

class UserManager(models.Manager):
	def date_valid(self, birthday):
		now = datetime.now()
		birthday = datetime.strptime(birthday, "%Y-%m-%d")
		if birthday > now:
			return False
		else:
			return True
	def validate(self, email):
		EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
		if not EMAIL_REGEX.match(email):
			return False
		else:
			return True
			
	def login_valid(self, email, password):
			user = User.objects.get(email = email)
			if user:
				password = password.encode()
				if bcrypt.hashpw(password, user.password.encode()) ==  user.password.encode():
					return True
				else:
					return False
			else:
				return False

	def register(self, first_name, last_name, password, confirm):
		NAME_REGEX = re.compile(r'^[a-zA-Z-]{2,}$')
		PASSWORD_REGEX = re.compile(r'^.{8,}$')
		if not NAME_REGEX.match(first_name):
			return False
		elif not NAME_REGEX.match(last_name):
			return False
		elif not PASSWORD_REGEX.match(password):
			return False
		elif  not password == confirm:
			return False
		else:		
			return True
class User(models.Model):
	first_name = models.CharField(max_length = 45)
	last_name = models.CharField(max_length = 45)
	email = models.CharField(max_length = 45)
	password = models.CharField(max_length = 255)
	birthday = models.DateField()
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = UserManager()

django_black_belt/retake_black_belt_test/apps/black_belt/views.py
from django.shortcuts import render, redirect
from ..login_registration.models import User
from .models import Poke
from django.core.urlresolvers import reverse
from django.db.models import Count


def index(request):
	context={
		"current_user": User.objects.get(id=request.session['id']),
		"pokemes": Poke.objects.filter(pokee__id = request.session['id']).values('poker__last_name').annotate(count = Count('poker')).order_by('-count'),
		"users": User.objects.exclude(id=request.session['id']).annotate(count = Count('pokee')), 
	}
	return render(request, 'black_belt/index.html', context)
def poke(request, id):
	poke = Poke.objects.create(poker = User.objects.get(id = request.session['id']), pokee = User.objects.get(id = id))
	return redirect(reverse('black_belt:my_index'))

django_black_belt/retake_black_belt_test/apps/login_registration/views.py
from django.shortcuts import render, redirect
from .models import User
import bcrypt
from django.core.urlresolvers import reverse

def index(request):
	try:
		request.session['message']
	except:
		request.session['message'] = ''
	return render(request, 'login_registration/index.html')
def register(request):
	email_validate = User.objects.validate(request.POST['email'])
	info_validate = User.objects.register(request.POST['first_name'],request.POST['last_name'],request.POST['password'], request.POST['confirm']) 
	date_validate = User.objects.date_valid(request.POST['birthday'])
	password = request.POST['password']
	if email_validate and info_validate and date_validate:
		request.session['message'] = ''
		request.session['first_name'] = request.POST['first_name']
		request.session['regorlogin'] = 'registered'
		password = password.encode('utf-8')
		hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		birthday = request.POST['birthday']
		email = request.POST['email']
		User.objects.create(email = email, first_name = first_name, last_name = last_name, password = hashed, birthday = birthday)
		request.session['id'] = User.objects.get(email = email).id
		return redirect('/success')
	elif not date_validate:
		request.session['message'] = "Birthday must be before today"
	elif not email_validate:
		request.session['message'] = "Email is not valid"
	elif not info_validate:
		request.session['message'] = "First Name required and must letters\r\n Last Name required and must have letters \r\n Password Required with no fewer than 8 characters and must match passwowrd confirmation"
	return redirect(reverse('logreg:my_index'))
def login(request):
	login_validate = User.objects.login_valid(request.POST['email'], request.POST['password'])
	if login_validate:
		request.session['id'] = User.objects.get(email=request.POST['email']).id
		request.session['message'] = ''
		request.session['first_name'] = User.objects.get(email=request.POST['email']).first_name
		request.session['regorlogin'] = 'logged in!'
		return redirect('/success')
	elif not login_validate:
		request.session['message']= 'Wrong login credentials'
	return redirect(reverse('black_belt:my_index'))
def success(request):
	return redirect(reverse('black_belt:my_index'))
def logout(request):
	request.session['message'] = ''
	request.session.pop('id')
	return redirect(reverse('logreg:my_index'))

django_black_belt/retake_black_belt_test/apps/black_belt/templates/black_belt/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Pokes</title>
	</head>
	<body>
		<a href = "{% url 'logreg:logout' %}">Logout</a>
		<h1>Welcome, {{current_user.first_name}}!</h1>
		<h2>{{pokemes | length}} People poked you</h2>
		<table>
			<tbody>
				{% for pokeme in pokemes %}
					<tr>
						<td>{{pokeme.poker__last_name}} poked you {{pokeme.count}} times.</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<h2>People you may want to poke:</h2>
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Alias</th>
					<th>Email Addresss</th>
					<th>Poke History</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users %}
					<tr>
						<td>{{user.first_name}}</td>
						<td>{{user.last_name}}</td>
						<td>{{user.email}}</td>
						<td>{{user.count}} pokes</td>
						<td><a href="{% url 'black_belt:my_poke' id=user.id %}"> <input type="button" value="Poke"></a></td>
					</tr>
				{% endfor %}
			</tbody>	
		</table>
	</body>
</html>

django_black_belt/retake_black_belt_test/apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login & Reg | Home</title>
	</head>
	<body>
		<h1>Registration</h1>
		{% if not request.session.message is '' %}
			<h3>{{request.session.message}}</h3>
		{% endif %}
		<form action ="/validate_register" method="post">{% csrf_token %}
			<label>Name:</label><input type = "text" name ="first_name"><br>
			<label>Alias:</label><input type = "text" name ="last_name"><br>
			<label>Email:</label><input type = "text" name="email"><br>
			<label>Password:</label><input type = "text" name = "password"><br>
			<label>Confirm:</label><input type = "text" name = "confirm"><br>
			<label>Date of Birth:</label><input type ="date" name="birthday"><br>
			<input type = "submit" value = "Register">
		</form>
		<h1>Login</h1>
		<form action ="/validate_login" method="post">{% csrf_token %}
			<label>Email:</label><input type = "text" name="email"><br>
			<label>Password:</label><input type = "text" name = "password"><br>
			<input type = "submit" value = "Login">
		</form>
	</body>
</html>

django_black_belt/retake_black_belt_test/apps/login_registration/templates/login_registration/success.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login & Reg | Success</title>
	</head>
	<body>
		<h1>Success! Welcome, {{request.session.first_name}}!</h1>
		<p>Successfully {{request.session.regorlogin}}</p>
	</body>
</html>